config/routes.rb
Rails.application.routes.draw do
	root "myarticles#index"

	resources :myarticles do
		resources :mycomments
	end
	#get "/myarticles", to: "myarticles#index"
	#get "/myarticles/:id", to:"myarticles#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myarticle.rb
class Myarticle < ApplicationRecord
	has_many  :mycomments

	validates :title, presence: true
	validates :body, presence: true, length: { minimum: 10 }
end

app/models/mycomment.rb
class Mycomment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/myarticles_controller.rb
class MyarticlesController < ApplicationController
  def index
	@articles = Myarticle.all
  end

  def show
	@article = Myarticle.find(params[:id])
  end

  def new
	@article = Myarticle.new
  end

  def create
	@article = Myarticle.new(myarticle_params)

	if @article.save
		redirect_to @article
	else 
		render :new, status: :unprocessable_entity
	end
  end

  def edit
	@article = Myarticle.find(params[:id])
  end

  def update
	@article = Myarticle.find(params[:id])

	if @article.update(myarticle_params)
		redirect_to @article
	else
		render :new, status: :unprocessable_entity
	end
  end

  def destroy
	@article = Myarticle.find(params[:id])
	@article.destroy
   
	redirect_to root_path, status: :see_other
     end

  private
  	def myarticle_params
		params.require(:myarticle).permit(:title, :body)
	end
end

app/controllers/mycomments_controller.rb
class MycommentsController < ApplicationController
	def create
		@article = Myarticle.find(params[:article_id])
		@comment = @article.mycomments.create(mycomment_params)
		redirect_to myarticle_path(@article)
	end

	private
		def mycomment_params
			params.require(:mycomment).permit(:commenter, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/myarticles_helper.rb
module MyarticlesHelper
end

app/helpers/mycomments_helper.rb
module MycommentsHelper
end

app/views/articles/index.html.erb
<h2> Hello world with ruby on rails</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/myarticles/_form.html.erb
<%=  form_with model: article do |form| %>
	<div>
		<%= form.label :title %> <br>
		<%= form.text_field :title %>
		<% article.errors.full_messages_for(:title).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div>
		<%= form.label :body %><br>
		<%= form.text_area :body %><br>
		<% article.errors.full_messages_for(:body).each do |message| %>
			<div><%= message %>
		<% end %>
	</div>

	<div>
		<%= form.submit %>
	</div>
<% end %>

app/views/myarticles/edit.html.erb
<h1> EDIT Article</h1>

<%= render "form", article: @article%>

app/views/myarticles/index.html.erb
<h1>Articles</h1>
<ul>
	<% @articles.each do |article| %>
		<li>
		<!-- <a href="<%= myarticle_path(article) %>"> -->
		<!-- <a href="<%= myarticle_url(article) %>">  -->
		<!-- <%= article.title%> -->
		<%= link_to article.title, article%>
		</a>
		</li>
	<% end %>
</ul>

<%= link_to "New Article", new_myarticle_path %>

app/views/myarticles/new.html.erb
<h1>NEW Article</h1>

<%= render "form", article: @article %>

app/views/myarticles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_myarticle_path(@article) %></li>
  <li><%= link_to "Destroy", myarticle_path(@article), data: {
                    method: :delete,
                    confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<% @article.mycomments.each do |comment| %>
	<p>
		<strong>Commenter:</strong>
		<%= comment.commenter %>
	</p>

	<p>
		<strong>Comment:</strong>
		<%= comment.body %>
	</p>
<% end %>


<h2>Add a comment: </h2>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
	<p>
		<%= form.label :commenter %> <br>
		<%= form.text_field :commenter %>
	</p>
	<p>
		<%= form.label :body %> <br>
		<%= form.text_area :body %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>